root = "."
tmp_dir = ".tmp"

[build]
cmd = "go build -o ./.tmp/main ./cmd/"
bin = "./.tmp/main"
full_bin = "./.tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["assets", ".tmp", "vendor"]
include_dir = []
include_file = [".env"]
exclude_file = []
delay = 1000
stop_on_error = true
log = "air.log"

[log]
time = false

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"

[misc]
clean_on_exit = true
